version: '3'
services:
  app:
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
      - "3001:3001"
    command: ["npm", "start"]
    user: "1000"
